import '../styles/globals.css'
import type { AppProps } from 'next/app';
import axios from 'axios';
import { store } from '../redux/store';
import { Provider } from 'react-redux';
import Head from 'next/head';



axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_PATH;

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
        <Head>
          <title>Backoffice</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <Component {...pageProps} />
    </Provider>
)}

export default MyApp
