import {
  Box, Grid, Typography, Modal, Button, useMediaQuery, IconButton,
  Collapse, Link, ListItemButton, ListItemText, ListItemIcon, Divider
} from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Item from '../src/Components/ProductItem';
import Form from '../src/Components/Form';
import Header from '../src/Components/Header';
import GoToLogIn from '../src/Components/GoToLogIn';
import List from '../src/Components/List';
import CloseIcon from '@mui/icons-material/Close';
import AccountCircleRoundedIcon from '@mui/icons-material/AccountCircleRounded';
import ExpandLess from '@mui/icons-material/ExpandLess';
import ExpandMore from '@mui/icons-material/ExpandMore';
import Router from 'next/router';
import { useSelector, useDispatch } from 'react-redux';
import { selectProducts, getAllProducts } from '../redux/slices/productSlice';
import { selectAdmin, logOut } from '../redux/slices/userSlice';
import type { AppDispatch } from  '../redux/store';


interface Data {
  _id: string,
  title: string,
  image: string,
  description: string,
  price: number,
  stock: boolean
}

interface Admin {
  token: string | null;
  name: string | null;
  role: number | null;
  loggedIn: boolean;
}

const Home: NextPage = () => {
  const products = useSelector(selectProducts);
  const { loggedAdmin } = useSelector(selectAdmin);
  const dispatch = useDispatch<AppDispatch>();
  const [open, setOpen] = useState<boolean>(false);
  const W400 = useMediaQuery('(min-width:400px)');
  const W700 = useMediaQuery('(min-width:700px)');

  useEffect(() => {
    if (loggedAdmin.loggedIn) {
      dispatch(getAllProducts())
    };
  }, [dispatch, loggedAdmin])
  const handleOpen = () => {
    setOpen(true)
  }
  const handleClose = () => {
    dispatch(getAllProducts())
    setOpen(false)
  }
  return (
    loggedAdmin.loggedIn
      ? (<Box
        display='flex'
        flexDirection='column'
        alignItems='center'
        minHeight='100vh'
        width='100vw'
        bgcolor='rgba(231, 230, 247, 0.5)'

      >
        <Head>
          <title>Web-B</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <Header />

        <Typography
          variant='h2'
          align='center'
        >
          Tablero de Control
        </Typography>

        <List products={products} />

        <Button
          variant='outlined'
          color='primary'
          sx={{
            margin: '6px'
          }}
          onClick={handleOpen}
        >
          AGREGAR
        </Button>
        <Modal
          open={open}
          onClose={handleClose}
          sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}
        >
          <>
            <Form add={true} />
            <Button
              variant='text'
              sx={{
                position: 'absolute',
                top: `${W400 ? '1rem' : '0.2rem'}`,
                right: '0.5rem',
                color: '#fff',
                border: '1px solid #000',

              }}
              onClick={handleClose}
            >
              <CloseIcon />
            </Button>
          </>
        </Modal>
      </Box>)
      : (
        <GoToLogIn />
      )
  )
}


export default Home
