import { Box, Grid, Typography, Modal, Button, useMediaQuery } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Item from '../src/Components/Item';
import Form from '../src/Components/Form';
import CloseIcon from '@mui/icons-material/Close';
import axios from 'axios';


interface Data{
  _id : string,
  title : string,
  image : string,
  description : string,
  price : number,
  stock : boolean
}
axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_PATH;
const Home: NextPage = () => {
  const [data, setData] = useState<Data[]>([]);
  const [open, setOpen] = useState<boolean>(false);
  const W400 = useMediaQuery('(min-width:400px)');
  

  useEffect(() => {
    const fetchData = async() => {
      
      setData(await axios(`/`).then(r => r.data));
    }
    fetchData();

  }, [])
  const handleOpen = () => {
    setOpen(true)
  }
  const handleClose = () => {
    setOpen(false)
  }
  return (
    <Box 
      display='flex'
      flexDirection='column'
      alignItems='center'
      minHeight='100vh'
      width='100vw'
      
    >
      <Head>
        <title>Web-B</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography
        variant='h2'
        align='center'
      >
        Tablero de Control
      </Typography>
      
      <Grid
        container
        width={W400 ? '80vw' : '100vw'}
        p={W400 ? '0.2rem' : '1rem'}
        sx={{
          boxShadow : '2px 2px 2px 1px rgba(0, 0, 0, 0.2)',
          borderRadius : '1rem'

        }}
      >
        {
          data.map((e : Data) => {
            return(
              <Item data={e} key={e._id} />
            )
          })
        }
        
      </Grid>
      <Button 
        variant='outlined'
        color='primary'
        sx={{
          margin : '6px'
        }}
        onClick={handleOpen}
      >
        AGREGAR
      </Button>
      <Modal
        open={open}
        onClose={handleClose}
        sx={{
          display : 'flex',
          alignItems : 'center',
          justifyContent : 'center'
        }}
      >
        <>
        <Form add={true} />
        <Button
            variant='text'
            sx={{
                position : 'absolute',
                top : `${W400 ? '1rem' : '0.2rem'}`,
                right : '0.5rem',
                color : '#fff',
                border : '1px solid #000',
               
            }}
            onClick={handleClose}
          >
            <CloseIcon  />
        </Button>
        </>
      </Modal>
    </Box>
  )
}

export default Home
