import { Box, Button, Container } from '@mui/material'
import { GetServerSideProps } from 'next';
import type { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios'; 
import socket from '../src/socket';
import { useEffect, useState } from 'react';

interface Data{
  _id : string,
  title : string,
  image : string,
  description : string,
  price : number,
  stock : boolean
}
interface Props {
  data : Data[]
}
/* https://www.mongodb.com/docs/drivers/node/current/usage-examples/changeStream/
trigger an alert when is a change in a database mongodbqwef */
const Home: NextPage<Props> = ({ data }) => {
  const[newData, setNewData] = useState([]);
  socket.on('data', (e) => console.log(e));

  useEffect(() => {
    socket.emit('connected');
  }, []); 

  const handleClick = async() => {
    setNewData(await axios.get('http://localhost:3001/').then(r => r.data))
  }

  return (
    
    <Box
      display='flex'
      flexDirection='column'
      alignItems='center'
      sx={{width : '100vw', height : '100vh'}}
      >
      <Head>
        <title>Web-A</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Lista de precios</h1>
      <Button onClick={handleClick} >Buscar</Button>
      <Box
        display='flex'
        flexWrap='wrap'
        border={1}
        sx={{width : '80vw', height : 'max-content'}}
      >
        {
          !newData.length ?
            data?.map((e : Data) => {
              return (
                <Box 
                  display='flex'
                  flexDirection='column'
                  alignItems='center'
                  m={2}
                  border={1}
                  sx={{width : '30%'}}
                  key={e._id}
                >
                  <h1>{e.title}</h1>
                  <p>{e.price}</p>
                  <pre>{e.description}</pre>
                  <p>{e.stock ? 'Hay stock' : 'No hay en stock'}</p>
                </Box>
              )
          }) : 
          newData?.map((e : Data) => {
            return (
              <Box 
                display='flex'
                flexDirection='column'
                alignItems='center'
                m={2}
                border={1}
                sx={{width : '30%'}}
                key={e._id}
              >
                <h1>{e.title}</h1>
                <p>{e.price}</p>
                <pre>{e.description}</pre>
                <p>{e.stock ? 'Hay stock' : 'No hay en stock'}</p>
              </Box>
            )
        })
        }

      </Box>
      
      

      
    </Box>
  )
}

export const getServerSideProps : GetServerSideProps = async () => {
  const data : Props = await axios.get('http://localhost:3001/').then(r  => r.data);
  return {
    props : {data}
  }
}

export default Home
