import { Box, Container } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <Box
      display='flex'
      flexDirection='column'
      alignItems='center'
      >
      <Head>
        <title>Web-A</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lista de precios</h1>
      
      

      
    </Box>
  )
}

export default Home
