import { Box, Button, Typography, useMediaQuery, Collapse, Skeleton } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios'; 
import socket from '../src/socket';
import Footer from '../src/components/Footer';
import Card from '../src/components/Card';
import MenuItem from '../src/components/MenuItem';
import MenuIcon from '@mui/icons-material/Menu';
import CloseIcon from '@mui/icons-material/Close';


interface Data{
  _id : string,
  title : string,
  image : string,
  description : string,
  price : number,
  stock : boolean
}

axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_PATH;
const Home: NextPage = () => {
  const [data, setData] = useState<Data[]>([]);
  const [open, setOpen] = useState<boolean>(false);
  const W850 = useMediaQuery('(min-width:750px)');
  const W500 = useMediaQuery('(min-width:500px)');

  const handleOpen = () => {
    setOpen(true);
  }
  const handleClose = () => {
    setOpen(false);
  }
  try{
    socket.on('server:changes', async () => setData(await axios.get(`/`).then(r => r.data)));

  } catch(e) {
    console.log(e);
  }

  useEffect(() => {

    const fetchData = async() => {
      setData(await axios.get(`/`).then(r => r.data));
      
    }
    fetchData();

  }, [])

  return (
    
    <Box
      display='flex'
      flexDirection='column'
      alignItems='center'
      sx={{width : '100vw', height : '100vh', overflowX : 'hidden'}}
      >
      <Head>
        <title>Web-A</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button 
        onClick={handleOpen}
        variant='outlined'
        color='info'
        sx={{
          position : 'absolute',
          top : '1rem',
          left : '1rem'
        }}

      >
        <MenuIcon />
      </Button>
      <Collapse orientation="horizontal" in={open} >
        <Box
          position='fixed'
          top={0}
          left='0%'
          height='100vh'
          width='100vw'
          sx={{
            background : 'transparent',
            zIndex : '100'
          }}
        >
          <Box
            display='flex'
            flexDirection='column'
            alignItems='center'
            height='100%'
            width={W500 ? W850 ? '40%' : '50%' : '100%'}
            sx={{
              background : 'rgba(0, 0, 0, 0.9)',
              borderTopRightRadius : '1rem',
              borderBottomRightRadius : '1rem',
              boxShadow : '2px 0 2px 1px rgba(0, 0, 0, 0.4)',
              transition : 'all 0.3s ease-in-out',
            }}
          >
            <Button 
              onClick={handleClose}
              variant='outlined'
              color='primary'
              sx={{
                alignSelf : 'flex-end',
                margin : '0.5rem'
              }}
            >
              <CloseIcon />
            </Button>
            <Box
              width='100%'
              onClick={handleClose}
            >

              <MenuItem data={'Sobre Nosostros'} />
            </Box>
            <Box
              width='100%'
              onClick={handleClose}
            >
              <MenuItem data={'Contacto'} />
            </Box>
          </Box>
        </Box>
      </Collapse>
      <Typography 
        variant='h2'
        my='2rem'
        mt={W500 ? '' : '4rem'}
        align='center'

      >
        Lista de precios
      </Typography>
      
      <Box
        display='flex'
        justifyContent='space-around'
        alignItems='center'
        flexWrap='wrap'
        mb='3rem'
        sx={{width : '80vw', minHeight : 'max-content'}}
      >
        {
          data?.length ? '' : (
            <Card data={{_id : 'string'}}/>
          )
        }
        {
            data?.map((e : Data) => {
              
              return <Card key={e._id} data={e} /> 
          })
        }

      </Box>
      
      

      <Footer />
    </Box>
  )
}



export default Home
